project_name: govm

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - binary: govm
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -X main.commit={{ .Commit }}
      - -X main.built={{ .Date }}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    ignore:
      - { goos: darwin, goarch: "386" }
      - { goos: windows, goarch: arm64 }

nfpms:
  - description: Go version manager
    # file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    id: packages
    file_name_template: "{{ .ConventionalFileName }}"
    maintainer: Harry Brown <harrybrown98@gmail.com>
    license: Apache 2.0
    vendor: Harry Brown
    dependencies: []
    suggests: []
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin
    prerelease: beta
    section: utils
    contents:
      - src: release/completion/bash/govm
        dst: /usr/share/bash-completion/completions/govm
      - src: release/completion/zsh/_govm
        dst: /usr/share/zsh/vendor-completions/_govm
      - src: release/completion/fish/govm.fish
        dst: /usr/share/fish/completions/govm.fish
    scripts:
      postinstall: scripts/postinstall.sh
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package

publishers:
  - name: hrry.me
    ids:
      - packages

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

