on:
  - push

name: ci

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ~1.19
    - run: go vet -v ./...
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        args: --disable unused

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ~1.19
    - name: Cache Dependencies
      uses: actions/cache@v2
      id: go-cache
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
          ~/go/bin
        key: ${{ runner.os }}_${{ runner.arch }}-${{ steps.go-version.outputs.version-used }}-build-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}_${{ runner.arch }}-${{ steps.go-version.outputs.version-used }}-build-
    - name: Install Go dependencies
      if: steps.go-cache.outputs.cache-hit != 'true'
      run: go mod download
    - name: Generate test files
      run: go generate ./...
    - name: Run tests
      run: go test -v ./...

  build:
    name: build
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ~1.19
    - name: Build Release
      uses: goreleaser/goreleaser-action@v2
      with:
        distribution: goreleaser
        version: v1.12.3
        args: release --rm-dist --snapshot
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload Build
      uses: actions/upload-artifact@v2
      with:
        name: govm
        path: dist/*

